[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    regression: Marker for regression tests.
    registration: Marker for registration tests.
    authorization: Marker for authorization tests.
    courses: Marker for tests within courses functionality.
    dashboard: Marker for tests on the dashboard page.